services:
  - type: web
    name: prob-forecasting-api
    env: docker
    region: oregon
    plan: free
    healthCheckPath: /health
    healthCheckProtocol: http
    envVars:
      - key: ENVIRONMENT
        value: production
